spring:
  datasource:
    url: jdbc:mariadb://192.168.0.7:3306/blog
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


token:
  secret:
    key: token_key